import type { Message, MessageCreateRequest, Uuid } from '@poolse/sdk';
import { useCallback, useEffect, useRef, useState } from 'react';
import { usePoolse } from './provider.js';

interface UseThreadState {
  /** Replies, oldest-first (the wire returns oldest-first; we don't flip). */
  replies: Message[];
  loading: boolean;
  error: Error | null;
  /** More older-than-current-page replies available on the server. */
  hasMore: boolean;
  /** Load the next page after the current newest reply. Idempotent if no more. */
  loadMore: () => Promise<void>;
  /**
   * Send a reply into this thread. Fills `reply_to_id` with the root
   * message id automatically; pass `body` (and any other
   * `MessageCreateRequest` fields) as you would to `useMessages.send`.
   */
  sendReply: (attrs: Omit<MessageCreateRequest, 'reply_to_id'>) => Promise<Message>;
}

const PAGE_SIZE = 50;

/**
 * Thread view rooted at `rootMessageId`. Loads replies oldest-first
 * with cursor pagination (`after: sequence`), subscribes to the
 * conversation channel's `message:new` event filtered by
 * `thread_root_id === rootMessageId`, and provides a `sendReply`
 * that wires `reply_to_id` for you.
 *
 * Like `useMessages`, the optimistic send uses the same id the
 * server will assign (auto-generated by the SDK), so the realtime
 * echo just upserts in place — no double-render.
 */
export function useThread(conversationId: Uuid, rootMessageId: Uuid): UseThreadState {
  const chat = usePoolse();
  const [replies, setReplies] = useState<Message[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);
  const [hasMore, setHasMore] = useState(true);

  // Cursor for `loadMore` — the highest sequence currently in state.
  const newestSequenceRef = useRef<number | null>(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setReplies([]);
    setError(null);
    setHasMore(true);
    newestSequenceRef.current = null;

    chat.messages
      .one(rootMessageId)
      .replies({ limit: PAGE_SIZE })
      .then((page) => {
        if (cancelled) return;
        setReplies(page.data);
        setHasMore(page.data.length === PAGE_SIZE);
        newestSequenceRef.current = page.data[page.data.length - 1]?.sequence ?? null;
        setLoading(false);
      })
      .catch((err: unknown) => {
        if (cancelled) return;
        setError(err instanceof Error ? err : new Error(String(err)));
        setLoading(false);
      });

    // Realtime: filter conversation messages for thread membership.
    const conv = chat.realtime.conversation(conversationId);
    const offNew = conv.onMessage((msg) => {
      if (msg.thread_root_id !== rootMessageId) return;
      setReplies((prev) => upsertById(prev, msg));
    });
    const offUpdated = conv.onMessageUpdated((msg) => {
      if (msg.thread_root_id !== rootMessageId) return;
      setReplies((prev) => prev.map((m) => (m.id === msg.id ? msg : m)));
    });
    const offDeleted = conv.onMessageDeleted((evt) => {
      setReplies((prev) =>
        prev.map((m) => (m.id === evt.id ? { ...m, deleted_at: evt.deleted_at, body: null } : m)),
      );
    });

    return () => {
      cancelled = true;
      offNew();
      offUpdated();
      offDeleted();
    };
  }, [chat, conversationId, rootMessageId]);

  const loadMore = useCallback(async () => {
    if (!hasMore || loading) return;
    const after = newestSequenceRef.current;
    if (after === null) return;
    const page = await chat.messages.one(rootMessageId).replies({ limit: PAGE_SIZE, after });
    if (page.data.length === 0) {
      setHasMore(false);
      return;
    }
    setReplies((prev) => [...prev, ...page.data]);
    setHasMore(page.data.length === PAGE_SIZE);
    newestSequenceRef.current = page.data[page.data.length - 1]?.sequence ?? after;
  }, [chat, rootMessageId, hasMore, loading]);

  const sendReply = useCallback(
    async (attrs: Omit<MessageCreateRequest, 'reply_to_id'>) => {
      const id = attrs.id ?? crypto.randomUUID();
      const tempMsg: Message = {
        id,
        tenant_id: '',
        conversation_id: conversationId,
        sender_id: null,
        type: attrs.type ?? 'text',
        body: attrs.body ?? null,
        reply_to_id: rootMessageId,
        thread_root_id: rootMessageId,
        mentions: attrs.mentions ?? [],
        reactions: {},
        edited_at: null,
        deleted_at: null,
        sequence: Number.MAX_SAFE_INTEGER,
        inserted_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      };
      setReplies((prev) => [...prev, tempMsg]);

      try {
        const sent = await chat.conversations.one(conversationId).messages.send({
          ...attrs,
          id,
          reply_to_id: rootMessageId,
        });
        setReplies((prev) => upsertById(prev, sent));
        return sent;
      } catch (err) {
        setReplies((prev) => prev.filter((m) => m.id !== id));
        throw err;
      }
    },
    [chat, conversationId, rootMessageId],
  );

  return { replies, loading, error, hasMore, loadMore, sendReply };
}

function upsertById(prev: Message[], msg: Message): Message[] {
  const idx = prev.findIndex((m) => m.id === msg.id);
  if (idx === -1) return [...prev, msg];
  const next = prev.slice();
  next[idx] = msg;
  return next;
}
